# JSON access log format for CloudWatch Logs Insights queries.
#   upstream_time_s = time spent in MapServer (FastCGI processing)
#   total_time_s    = full nginx request time (includes client transfer)
log_format json_metrics escape=json '{'
    '"timestamp":"$time_iso8601",'
    '"remote_addr":"$remote_addr",'
    '"method":"$request_method",'
    '"uri":"$uri",'
    '"args":"$args",'
    '"status":$status,'
    '"size":$body_bytes_sent,'
    '"upstream_time_s":"$upstream_response_time",'
    '"total_time_s":$request_time'
'}';

log_format cog_cache_metrics escape=json '{'
    '"timestamp":"$time_iso8601",'
    '"remote_addr":"$remote_addr",'
    '"method":"$request_method",'
    '"uri":"$uri",'
    '"status":$status,'
    '"size":$body_bytes_sent,'
    '"range":"$http_range",'
    '"cache_status":"$upstream_cache_status",'
    '"upstream_time_s":"$upstream_response_time",'
    '"total_time_s":$request_time'
'}';
